### ISSUE TITLE
Move sanity-data plugin to @app-boilerplate

### ISSUE THREAD

**Issue by kennedyrose** [smarterlabs/labs#50]

**Comment by tbaustin** [comment]
Just move this or move into a gatsby plugin?

**Comment by kennedyrose** [comment]
I think just move it into the @app-boilerplate namespace and make sure everything is pointing to it correctly.

**Comment by tbaustin** [comment]
Here is the mirrored repo: https://github.com/tbaustin/labs/pull/1

**Comment by kennedyrose** [comment]
You should be able to do a pull request from there to this repo.
