### ISSUE TITLE
Make boilerplate pull content from markdown by default

### ISSUE THREAD

**Issue by kennedyrose** [smarterlabs/labs#68]
Maybe check for some kind of Sanity key in the environment. If the key exists, use markdown, otherwise use Sanity.

**Comment by tbaustin** [comment]
I was thinking of this work flow. 
- Check to see if sanity key exist
- If key exist check to see if homepage exist from sanity > if it does create the page from sanity
- If key does not exist or there is no page from sanity check to see if there is a markdown page > if markdown page exist create page from markdown
- if key does not exist and markdown page does not exist > make a default page for homepage
