### ISSUE TITLE
Gatsby Cloudinary plugin

### ISSUE THREAD

**Issue by kennedyrose** [smarterlabs/labs#7]

**Comment by tbaustin** [comment]
https://github.com/Chuloo/gatsby-source-cloudinary

**Comment by kennedyrose** [comment]
I need something that does transformations too.

**Comment by tbaustin** [comment]
> I need something that does transformations too.

Just want to clarify on this, are we talking so you can use `gatsby-image` out of the box with cloudinary like so:

```
query {
 allCloudinary {
   url {
    childImageSharp {
     fluid(maxWidth: 400){
      ...GatsbyImageSharpFluid_noBase64
    }
   }
  }
 }
}
```

Or something just with cloudinary query transformations?

**Comment by kennedyrose** [comment]
Kind of both. It should spit out the same schema that the Gatsby image fragments do so they can be used with `gatsby-image`, however it should output Cloudinary URLs instead of the Gatsby ones. I think some of the other Gatsby CMS plugins do something similar for their images.

**Comment by tbaustin** [comment]
I'll try to tackle this one! May take a bit haha.

**Comment by kennedyrose** [comment]
Yeah, it's definitely one of the trickier issues. But it would give major benefits if we got the performance boost from gatsby-image but with the hosting from Cloudinary. Being able to query a bucket based on tags or something would be great too.
